### ISSUE TITLE
Cannot bump patch past 1

### ISSUE THREAD

**Issue by joncrlsn** [guilhem/bump#5]
If my tag is 0.20.0, `bump patch` will bump it to 0.20.1.

However, if I try running it again, `bump patch` returns this:
```
0.20.1
2021/03/02 10:43:19 fail to create tag: tag already exists
```

**Comment by guilhem** [comment]
Ok, I found the problem, as both patch are on the same commit, they have the same date and comparison fail.
https://github.com/guilhem/bump/blob/e934d5578178677da09827ed7e6c084ffe2ac090/pkg/git/git.go#L143

Fixing it
